// flow-typed signature: 84d15ee4c35d9ec58bccdb14a7f76329
// flow-typed version: <<STUB>>/crypto_v^1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'crypto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'crypto' {
  declare module.exports: any;
}
