// flow-typed signature: 18ec11a0f10f2144a59061084306e019
// flow-typed version: <<STUB>>/dynamic-cdn-webpack-plugin_v^4.0.0-rc.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dynamic-cdn-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dynamic-cdn-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dynamic-cdn-webpack-plugin/lib/get-resolver' {
  declare module.exports: any;
}

declare module 'dynamic-cdn-webpack-plugin/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dynamic-cdn-webpack-plugin/index' {
  declare module.exports: $Exports<'dynamic-cdn-webpack-plugin'>;
}
declare module 'dynamic-cdn-webpack-plugin/index.js' {
  declare module.exports: $Exports<'dynamic-cdn-webpack-plugin'>;
}
declare module 'dynamic-cdn-webpack-plugin/lib/get-resolver.js' {
  declare module.exports: $Exports<'dynamic-cdn-webpack-plugin/lib/get-resolver'>;
}
declare module 'dynamic-cdn-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'dynamic-cdn-webpack-plugin/lib/index'>;
}
