// flow-typed signature: bd4e38ecfd79e968fe766f95da4fe1b7
// flow-typed version: <<STUB>>/module-to-cdn_v^3.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'module-to-cdn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'module-to-cdn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'module-to-cdn/index' {
  declare module.exports: $Exports<'module-to-cdn'>;
}
declare module 'module-to-cdn/index.js' {
  declare module.exports: $Exports<'module-to-cdn'>;
}
