// flow-typed signature: 25bbd976e5ff44544e051151c3a8ccb0
// flow-typed version: <<STUB>>/sticky-session_v^1.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sticky-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sticky-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sticky-session/lib/sticky-session' {
  declare module.exports: any;
}

declare module 'sticky-session/lib/sticky/api' {
  declare module.exports: any;
}

declare module 'sticky-session/lib/sticky/master' {
  declare module.exports: any;
}

declare module 'sticky-session/test/100-connections-test' {
  declare module.exports: any;
}

declare module 'sticky-session/test/fork-options-test' {
  declare module.exports: any;
}

declare module 'sticky-session/test/graceful-close-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sticky-session/lib/sticky-session.js' {
  declare module.exports: $Exports<'sticky-session/lib/sticky-session'>;
}
declare module 'sticky-session/lib/sticky/api.js' {
  declare module.exports: $Exports<'sticky-session/lib/sticky/api'>;
}
declare module 'sticky-session/lib/sticky/master.js' {
  declare module.exports: $Exports<'sticky-session/lib/sticky/master'>;
}
declare module 'sticky-session/test/100-connections-test.js' {
  declare module.exports: $Exports<'sticky-session/test/100-connections-test'>;
}
declare module 'sticky-session/test/fork-options-test.js' {
  declare module.exports: $Exports<'sticky-session/test/fork-options-test'>;
}
declare module 'sticky-session/test/graceful-close-test.js' {
  declare module.exports: $Exports<'sticky-session/test/graceful-close-test'>;
}
